# ==========================================
# GENERAL SETTINGS
# ==========================================
set -g prefix C-s
set -g mouse on
set -g base-index 0
setw -g pane-base-index 0
set -g status-position bottom
set -g status-interval 1
set -g set-clipboard on

# Reload config
unbind r
bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"

# Pane navigation
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# ==========================================
# PLUGINS LIST
# ==========================================
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-cpu'

# ==========================================
# CATPPUCCIN THEME SETTINGS 
# ==========================================
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_text "#W"         
set -g @catppuccin_window_current_text "#W"
set -g @catppuccin_window_status "icon"
set -g @catppuccin_window_current_background "#{@thm_mauve}"

# ==========================================
# STATUS BAR LAYOUT 
# ==========================================
set -g status-left ""
set -g status-right ""
set -g status-right-length 100

# 1. Directory Module
#set -g status-right "#{E:@catppuccin_status_directory}"

# 2. Session Module
set -ag status-right "#{E:@catppuccin_status_session}"

# 3. Forced IST Time Pill
# This manually builds the pill: Left-Semi-Circle | Icon Block | Time Text
set -ag status-right "#[fg=#89b4fa,bg=default]#[fg=#1e1e2e,bg=#89b4fa,bold]󱑒 #[fg=#89b4fa,bg=#313244] #(TZ='Asia/Kolkata' date +%%H:%%M) "

# 4. CPU Pill
set -ag status-right "#[fg=#89b4fa,bg=#313244]#[fg=#1e1e2e,bg=#89b4fa,bold] #[fg=#89b4fa,bg=#313244] #{cpu_percentage} "


# ==========================================
# 6. INITIALIZE TPM
# ==========================================
run '~/.config/tmux/plugins/tpm/tpm'

# ==========================================
# display-popup window
# ==========================================
set -g popup-style 'bg=default'
set -g popup-border-lines rounded
set -g popup-border-style 'bg=default,fg=#f5deb3'

#lazygit
bind C-y display-popup \
    -d "#{pane_current_path}" \
    -w 80% \
    -h 80% \
    -E "lazygit"


# create-session
bind C-n display-popup \
    -E "bash -c 'read -p \"Session name: \" name; tmux new-session -d -s \"\$name\" 2>/dev/null; tmux switch-client -t \"\$name\"'"

# sessionlist and choose session
bind C-f display-popup -E "tmux list-sessions -F '#{session_name}' | grep -v \"^$(tmux display-message -p '#S')\$\" | fzf --reverse | xargs tmux switch-client -t"

# file manager
bind C-r display-popup \
    -w 80% \
    -h 80% \
    -E "ranger"

# new display-popup new-window
bind C-p display-popup -E
